import { describe, expect, it } from 'vitest';

import { parseGCodeProgram } from '../gcodeParser';

describe('parseGCodeProgram', () => {
  it('does not parse setup modal commands as motion', () => {
    const result = parseGCodeProgram(['G21', 'G17', 'G90', 'G0 X1 Y2'].join('\n'));

    expect(result.path).toEqual([
      {
        type: 'rapid',
        x: 1,
        y: 2,
        line: 4
      }
    ]);
    expect(result.stats.linearMoves).toBe(1);
    expect(result.stats.arcMoves).toBe(0);
  });

  it('parses header/body/footer programs generated by the DXF import flow', () => {
    const result = parseGCodeProgram(
      [
        '%',
        'G90 G21 G17 G40',
        'G54',
        'G0 X0.000 Y0.000',
        'G1 X10.000 Y0.000',
        'G3 X20.000 Y10.000 I0.000 J10.000',
        'G40',
        'M30',
        '%'
      ].join('\n')
    );

    expect(result.path).toHaveLength(3);
    expect(result.path[0]).toMatchObject({ type: 'rapid', x: 0, y: 0, line: 4 });
    expect(result.path[1]).toMatchObject({ type: 'cut', x: 10, y: 0, line: 5 });
    expect(result.path[2]).toMatchObject({
      type: 'arc',
      startX: 10,
      startY: 0,
      endX: 20,
      endY: 10,
      centerX: 10,
      centerY: 10,
      clockwise: false,
      line: 6
    });
    expect(result.stats).toMatchObject({
      arcMoves: 1,
      linearMoves: 2,
      processedLines: 9
    });
    expect(result.warnings).toEqual([]);
  });

  it('keeps exported ISO headers out of the motion path', () => {
    const result = parseGCodeProgram(
      [
        '%',
        'N10 G92',
        'N20 G60',
        'N30 G38',
        'N40 G42 D0',
        'N50 G90',
        'N60 G0 X0.000 Y0.000',
        'N70 G1 X1.000 Y0.000 F1000',
        'N80 M02'
      ].join('\n')
    );

    expect(result.path.map((point) => point.type)).toEqual(['position', 'rapid', 'cut']);
    expect(result.path.at(-1)).toMatchObject({
      type: 'cut',
      x: 1,
      y: 0,
      line: 8
    });
    expect(result.stats.arcMoves).toBe(0);
  });

  it('parses signed, spaced, leading-decimal, and scientific coordinate values', () => {
    const result = parseGCodeProgram(['G0 X +.5 Y -1.25', 'G2 X1e0 Y0 I +.25 J1.25e0'].join('\n'));

    expect(result.path[0]).toMatchObject({
      type: 'rapid',
      x: 0.5,
      y: -1.25
    });
    expect(result.path[1]).toMatchObject({
      type: 'arc',
      endX: 1,
      endY: 0,
      centerX: 0.75,
      centerY: 0
    });
  });

  it('supports modal coordinate-only continuation lines and compact machine output', () => {
    const result = parseGCodeProgram(['G01X1Y1', 'X2Y1', 'G02X2Y1I0J-1'].join('\n'));

    expect(result.path).toHaveLength(3);
    expect(result.path[1]).toMatchObject({ type: 'cut', x: 2, y: 1, line: 2 });
    expect(result.path[2]).toMatchObject({
      type: 'arc',
      startX: 2,
      startY: 1,
      endX: 2,
      endY: 1,
      centerX: 2,
      centerY: 0,
      clockwise: true
    });
    expect(result.bounds).toMatchObject({
      minX: 1,
      maxX: 3,
      minY: -1,
      maxY: 1
    });
  });

  it('continues modal motion across non-motion M-code commands', () => {
    const result = parseGCodeProgram(
      ['G0 X0 Y0', 'G1 X1 Y0', 'X2 Y0', 'G3 X2 Y1 I1 J0', 'M01', 'X1 Y1 I1 J1'].join('\n')
    );

    expect(result.path.map((point) => point.type)).toEqual([
      'rapid',
      'cut',
      'cut',
      'arc',
      'arc'
    ]);
    expect(result.path[2]).toMatchObject({
      type: 'cut',
      x: 2,
      y: 0,
      line: 3
    });
    expect(result.path[4]).toMatchObject({
      type: 'arc',
      startX: 2,
      startY: 1,
      endX: 1,
      endY: 1,
      centerX: 3,
      centerY: 2,
      clockwise: false,
      line: 6
    });
    expect(result.warnings).toEqual([]);
  });

  it('ignores non-motion M-code control commands without warnings', () => {
    const result = parseGCodeProgram(['M28', 'G0 X0 Y0', 'M01', 'G1 X1 Y0', 'M02'].join('\n'));

    expect(result.path.map((point) => point.type)).toEqual(['rapid', 'cut']);
    expect(result.warnings).toEqual([]);
  });

  it('parses compact machine output without spaces between commands and parameters', () => {
    const result = parseGCodeProgram(
      ['N10 (program name)', 'G92X0Y0', 'G60', 'G41D0', 'G01X6500Y0', 'G03X6500Y5477I0J0'].join('\n')
    );

    expect(result.path.map((point) => point.type)).toEqual(['position', 'cut', 'arc']);
    expect(result.path[0]).toMatchObject({
      type: 'position',
      x: 0,
      y: 0,
      line: 2
    });
    expect(result.path[1]).toMatchObject({
      type: 'cut',
      x: 6500,
      y: 0,
      line: 5
    });
    expect(result.path[2]).toMatchObject({
      type: 'arc',
      startX: 6500,
      startY: 0,
      endX: 6500,
      endY: 5477,
      centerX: 0,
      centerY: 0,
      clockwise: false,
      line: 6
    });
    expect(result.warnings).toEqual([]);
  });

  it('preserves omitted axes when G92 sets only one coordinate after motion', () => {
    const xOnly = parseGCodeProgram(['G0 X10 Y20', 'G92 X5', 'G1 X6'].join('\n'));
    const yOnly = parseGCodeProgram(['G0 X10 Y20', 'G92 Y7', 'G1 Y8'].join('\n'));

    expect(xOnly.path.at(-1)).toMatchObject({
      type: 'cut',
      x: 6,
      y: 20,
      line: 3
    });
    expect(yOnly.path.at(-1)).toMatchObject({
      type: 'cut',
      x: 10,
      y: 8,
      line: 3
    });
  });

  it('treats a plain G92 after motion as an origin reset', () => {
    const result = parseGCodeProgram(['G0 X10 Y20', 'G92', 'G1 X6'].join('\n'));

    expect(result.path.at(-1)).toMatchObject({
      type: 'cut',
      x: 6,
      y: 0,
      line: 3
    });
  });

  it('uses G60 absolute IJ center mode for subsequent arcs', () => {
    const result = parseGCodeProgram(['G0 X10 Y0', 'G60', 'G3 X20 Y10 I10 J10'].join('\n'));

    expect(result.path[1]).toMatchObject({
      type: 'arc',
      startX: 10,
      startY: 0,
      endX: 20,
      endY: 10,
      centerX: 10,
      centerY: 10,
      clockwise: false
    });
  });

  it('falls back to incremental IJ when absolute IJ mode has an incomplete arc center', () => {
    const result = parseGCodeProgram(['G0 X10 Y0', 'G60', 'G3 X20 Y10 I5'].join('\n'));

    expect(result.path[1]).toMatchObject({
      type: 'arc',
      startX: 10,
      startY: 0,
      endX: 20,
      endY: 10,
      centerX: 15,
      centerY: 0,
      clockwise: false,
      line: 3
    });
    expect(result.warnings).toEqual([
      {
        line: 3,
        message: 'Arc center missing I or J in absolute IJ mode; falling back to incremental IJ.',
        type: 'warning'
      }
    ]);
  });
});
