import type { WireEdmExecutionEvent } from '@/domain/execution-plan/executionPlan';
import type { Point2 } from '@/domain/path-intel/types';

export interface ExecutionSpatialAction {
  readonly key: string;
  readonly eventId: string;
  readonly eventKind: WireEdmExecutionEvent['kind'];
  readonly operationId: string | null;
  readonly point: Point2;
  readonly label: string;
  readonly detail: string;
  readonly pause: 'authored' | 'generated-manual-thread' | 'emitted-post' | null;
  readonly emittedPauseCommandIds: readonly string[];
  readonly stopId?: string;
}

/** Walk events in execution order; a thread or separation occurs at the last machine point. */
export function executionSpatialActions(
  events: readonly WireEdmExecutionEvent[],
  sourceOperationId: (executionOperationId: string) => string | null,
  emittedPauseCommands: ReadonlyMap<string, readonly string[]> | null = null
): ExecutionSpatialAction[] {
  const actions: ExecutionSpatialAction[] = [];
  let current: Point2 | null = null;
  const separationByOperation = new Map<string, string>();
  const repeatedKeys = new Map<string, number>();
  for (const event of events) {
    const emittedPauseCommandIds = emittedPauseCommands?.get(event.id) ?? [];
    if (event.kind === 'program-start') current = event.initialWirePosition;
    if (event.kind === 'position') current = event.to;
    if (event.kind === 'motion') current = event.end;
    if (event.kind === 'program-stop') current = event.point;
    if (event.kind === 'wire-separate' && event.operationId) {
      separationByOperation.set(event.operationId,
        event.method === 'automatic' ? 'automatic separation before positioning' : 'manual separation before positioning');
    }
    if (event.kind === 'position' && event.operationId && event.separatesWire) {
      separationByOperation.set(event.operationId, 'automatic separation during positioning');
    }
    const point = event.kind === 'program-start' ? event.initialWirePosition
      : event.kind === 'position' ? event.to
      : event.kind === 'motion' ? event.end
      : event.kind === 'program-stop' ? event.point
      : event.kind === 'wire-thread' || event.kind === 'wire-separate' ||
        emittedPauseCommandIds.length > 0 ? current : null;
    if (!point) continue;
    const operationId = event.operationId ? sourceOperationId(event.operationId) : null;
    const source = event.trace.find((trace) => trace.kind === 'program-stop' ||
      trace.kind === 'segment' || trace.kind === 'transition');
    const identity = source?.kind === 'program-stop' ? `stop:${source.operationId}:${source.stopId}`
      : source?.kind === 'segment'
        ? `segment:${source.operationId}:${source.segmentId}:${source.sourceRange.start}:${source.sourceRange.end}:${event.kind}`
        : source?.kind === 'transition'
          ? `transition:${source.operationId}:${source.role}:${event.kind}`
          : `${operationId ?? 'program'}:${event.kind}`;
    const occurrence = repeatedKeys.get(identity) ?? 0;
    repeatedKeys.set(identity, occurrence + 1);
    const key = occurrence ? `${identity}:${occurrence}` : identity;
    const pause = event.kind === 'program-stop' ? 'authored'
      : event.kind === 'wire-thread' && event.method === 'manual' ? 'generated-manual-thread'
      : emittedPauseCommandIds.length > 0 ? 'emitted-post' : null;
    const label = event.kind === 'program-stop' ? 'Authored stop'
      : pause === 'generated-manual-thread' ? 'Manual rethread pause'
      : event.kind === 'position' ? 'Position wire'
      : event.kind === 'wire-thread' ? 'Thread wire automatically'
      : event.kind === 'wire-separate' ? 'Separate wire'
      : event.kind === 'program-start' ? 'Initial wire'
      : event.kind === 'motion' ? event.role === 'entry' ? 'Entry end'
        : event.role === 'exit' ? 'Exit end' : 'Cut endpoint' : event.kind;
    const displayLabel = pause === 'emitted-post' ? `Controller pause · ${label}` : label;
    const detail = pause === 'generated-manual-thread'
      ? `Generated by Between Contours · ${event.operationId
        ? separationByOperation.get(event.operationId) ?? 'wire already separated' : 'wire already separated'} · operator threads the wire before compensation · ${emittedPauseCommandIds.length
          ? 'confirmed in generated program'
          : emittedPauseCommands ? 'no pause in generated program' : 'generate a controller program to verify the pause'}`
      : pause === 'authored' ? `Authored in Program Stops · ${emittedPauseCommandIds.length
        ? 'confirmed in generated program' : emittedPauseCommands ? 'no pause in generated program' : 'generate a controller program to verify the pause'}`
      : pause === 'emitted-post' ? 'Confirmed in generated program'
      : event.kind === 'wire-thread' ? emittedPauseCommands
        ? 'Automatic threading · no pause in generated program'
        : 'Automatic threading · generate a controller program to verify machine-specific pauses'
      : 'Derived machining action';
    actions.push({ key, eventId: event.id, eventKind: event.kind, operationId,
      point, label: displayLabel, detail, pause, emittedPauseCommandIds,
      ...(event.kind === 'program-stop' ? { stopId: event.stopId } : {}) });
  }
  return actions;
}
