import { Download } from 'lucide-react';
import type { ReactNode } from 'react';

import { Button } from '@/components/ui/button';
import type { ImportDxfProjectResult } from '@/domain/dxf/importDxfProject';

interface LatestDxfImportPanelProps {
  children?: ReactNode;
  latestImport: ImportDxfProjectResult | null;
  onDownloadLatestProgram: () => void;
  onOpenLatestImportInEditor: () => void;
}

export function LatestDxfImportPanel({
  children,
  latestImport,
  onDownloadLatestProgram,
  onOpenLatestImportInEditor
}: LatestDxfImportPanelProps) {
  const pathMessages =
    latestImport?.pathDiagnostics
      .concat(latestImport.postDiagnostics)
      .map((diagnostic) => diagnostic.message) ?? [];
  const allWarnings = latestImport ? [...latestImport.parseResult.warnings, ...pathMessages] : [];

  return (
    <div className="grid min-h-0 grid-rows-[auto_minmax(0,1fr)] border border-border bg-card">
      <div className="h-8 border-b border-border px-3 py-2">
        <h3 className="font-mono text-xs font-semibold">Latest DXF Import</h3>
      </div>
      <div className="min-h-0 overflow-auto p-3 font-mono text-[11px]">
        {latestImport ? (
          <div className="space-y-3">
            <dl className="grid grid-cols-[88px_1fr] gap-x-3 gap-y-2">
              <dt className="text-muted-foreground">Project</dt>
              <dd className="truncate">{latestImport.project.name}</dd>
              <dt className="text-muted-foreground">Entities</dt>
              <dd>{latestImport.entityCount}</dd>
              <dt className="text-muted-foreground">Warnings</dt>
              <dd>{allWarnings.length}</dd>
              <dt className="text-muted-foreground">Contours</dt>
              <dd>{latestImport.pathDocument.contours.length}</dd>
              <dt className="text-muted-foreground">Export</dt>
              <dd className="truncate">
                {latestImport.project.generated.files.at(-1)?.path ?? 'UPID on demand'}
              </dd>
            </dl>
            {allWarnings.length > 0 && (
              <div className="border border-amber-500/50 bg-amber-500/10 p-2 text-amber-200">
                {allWarnings.join('\n')}
              </div>
            )}
            <div className="flex flex-wrap gap-2">
              <Button onClick={onOpenLatestImportInEditor} variant="default">
                Open in Editor
              </Button>
              <Button onClick={onDownloadLatestProgram} variant="outline">
                <Download />
                Download Program
              </Button>
            </div>
            {latestImport.generatedBody && (
              <pre className="max-h-[360px] overflow-auto border border-border bg-background/70 p-2 text-[10px] leading-5 text-foreground">
                {latestImport.generatedBody}
              </pre>
            )}
          </div>
        ) : (
          <dl className="grid grid-cols-[90px_1fr] gap-x-3 gap-y-2">
            <dt className="text-muted-foreground">Manifest</dt>
            <dd>workbench.json</dd>
            <dt className="text-muted-foreground">Profiles</dt>
            <dd>Active machine profile</dd>
            <dt className="text-muted-foreground">Folders</dt>
            <dd>imports, generated, exports, templates, machines, editor, projects</dd>
            <dt className="text-muted-foreground">Feeds</dt>
            <dd>Not generated by default</dd>
          </dl>
        )}
        {children}
      </div>
    </div>
  );
}
