import { expect, test } from '@playwright/test';
import { confirmPendingDxfImport } from './dxf-import';

test('confirms the active partial exit, persists review, and undoes revocation', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Go Build!', exact: true }).click();
  await page.getByLabel('DXF file').setInputFiles('examples/robofil-100-v2/no-lead-rectangle.dxf');
  await confirmPendingDxfImport(page);
  await page.getByRole('button', { name: 'Machining menu' }).click();
  await page.locator('[data-editor-workflow-command="machining.entry-exit"]').click();
  await page.getByLabel('Exit X', { exact: true }).fill('-3');
  await page.getByLabel('Exit Y', { exact: true }).fill('0');
  await page.getByRole('button', { name: 'Set straight exit', exact: true }).click();
  await page.locator('[data-editor-workflow-actions="machining.entry-exit"] button[aria-label^="Save "]').click();
  await page.getByRole('button', { name: 'Machining menu' }).click();
  await page.locator('[data-editor-workflow-command="machining.participation"]').click();
  await page.getByLabel('Machining span start', { exact: true }).fill('0.6');
  await page.getByLabel('Machining span end', { exact: true }).fill('1');
  await page.getByRole('button', { name: 'Mark inactive reference', exact: true }).click();
  const review = page.getByRole('button', { name: 'Review derived partial exit', exact: true });
  await expect(review).toHaveText('Review partial exit');
  await expect(review.locator('..')).toContainText('(6.000, 0.000) to (-3.000, 0.000) mm');
  await review.click();
  await expect(review).toHaveText('Exit reviewed · revoke');
  await page.screenshot({ path: 'tmp/cam-audit/09-partial-exit-review.png', fullPage: true });
  await page.locator('[data-editor-workflow-actions="machining.participation"] button[aria-label^="Save "]').click();
  await page.getByRole('button', { name: 'Save active document', exact: true }).click();
  await page.getByRole('button', { name: 'Back to Dashboard' }).click();
  await page.reload();
  await page.getByRole('button', { name: /Open project .* in editor/ }).click();
  await page.getByRole('button', { name: 'Machining menu' }).click();
  await page.locator('[data-editor-workflow-command="machining.participation"]').click();
  await expect(review).toHaveText('Exit reviewed · revoke');
  await review.click();
  await expect(review).toHaveText('Review partial exit');
  await page.locator('[data-editor-workflow-actions="machining.participation"] button[aria-label^="Save "]').click();
  await page.getByRole('button', { name: 'Undo active document change', exact: true }).click();
  await page.getByRole('button', { name: 'Machining menu' }).click();
  await page.locator('[data-editor-workflow-command="machining.participation"]').click();
  await expect(review).toHaveText('Exit reviewed · revoke');
});
