// Generated by npm run post:docs:generate. Do not edit.
export type PostPropertyValue = boolean | number | string;
export type Point2 = Readonly<{ x: number; y: number }>;
export type ExecutionSourceRef =
  | Readonly<{ kind: 'program' }>
  | Readonly<{ kind: 'operation'; operationId: string }>
  | Readonly<{ kind: 'segment'; operationId: string; segmentId: string; sourceRange: Readonly<{ start: number; end: number }> }>
  | Readonly<{ kind: 'transition'; operationId: string; role: 'entry' | 'exit' | 'position' | 'threading' }>
  | Readonly<{ kind: 'program-stop'; operationId: string; stopId: string }>;
export type SourceTrace = readonly [ExecutionSourceRef, ...ExecutionSourceRef[]];

export interface EventBase {
  readonly id: string;
  readonly ordinal: number;
  readonly operationId: string | null;
  readonly trace: SourceTrace;
}

export type WireEdmPostEvent =
  | (EventBase & { readonly kind: 'program-start'; readonly initialWirePosition: Point2 })
  | (EventBase & { readonly kind: 'operation-start'; readonly name: string; readonly orderIndex: number })
  | (EventBase & { readonly kind: 'pass-start'; readonly passId: string; readonly passOrdinal: 1; readonly purpose: 'single-cut'; readonly technology: { readonly kind: 'none' } })
  | (EventBase & { readonly kind: 'wire-continue' })
  | (EventBase & { readonly kind: 'wire-separate'; readonly method: 'manual' | 'automatic' })
  | (EventBase & { readonly kind: 'wire-thread'; readonly method: 'manual' | 'automatic' })
  | (EventBase & { readonly kind: 'position'; readonly from: Point2; readonly to: Point2; readonly separatesWire?: true })
  | (EventBase & { readonly kind: 'compensation-start'; readonly wireSide: 'left' | 'right'; readonly keptMaterial: 'inside' | 'outside' | null; readonly source: 'automatic' | 'manual' })
  | (EventBase & { readonly kind: 'motion'; readonly motion: 'linear' | 'circular'; readonly role: 'entry' | 'contour' | 'exit'; readonly start: Point2; readonly end: Point2; readonly center?: Point2; readonly clockwise?: boolean; readonly fullCircle?: boolean; readonly sourceSegmentId: string | null; readonly sourceRange?: { readonly start: number; readonly end: number } })
  | (EventBase & { readonly kind: 'program-stop'; readonly stopId: string; readonly placement: 'before-entry' | 'after-positioning' | 'before-operation-end' | 'after-contour' | 'after-exit' | 'after-contour-distance'; readonly reason: 'operator-check' | 'part-retention' | 'manual'; readonly note: string | null; readonly point: Point2 })
  | (EventBase & { readonly kind: 'compensation-end' })
  | (EventBase & { readonly kind: 'pass-end'; readonly passId: string })
  | (EventBase & { readonly kind: 'operation-end' })
  | (EventBase & { readonly kind: 'program-end' });

export interface WireEdmPostApi {
  getProperty(name: string): PostPropertyValue;
  /** Non-moving commands only, during a non-motion event. */
  emitCommand(commandId: string, parameters: Readonly<Record<string, string | number>>): void;
  emitMotion(commandId: string, parameters: Readonly<Record<string, number>>): void;
  consume(reason: string): void;
}

export interface WireEdmPostHandler {
  onEvent(event: WireEdmPostEvent): void;
}

export declare function createPost(api: WireEdmPostApi): WireEdmPostHandler;
