import type { MachineDefinition, MachinePostBinding } from '@/domain/machine-definition/machineDefinition';
import { canonicalJson } from '@/domain/post-processor/canonicalJson';
import { serializeControllerOutput } from '@/domain/post-processor/controllerOutput';
import type { PostInstallation } from '@/domain/post-processor/postLibrary';
import type { PostPropertyValue } from '@/domain/post-processor/postProperties';
import type { ControllerProgramArtifact } from './controllerArtifact';
import type { MachinePhysicalSnapshot } from './savedWireEdmJobRevision';
import type { GCodeInspectionOptions } from '@/domain/editor/gcodeInspectionTypes';
import { validateGCodeInspectionSource } from '@/domain/editor/gcodeInspectionSource';

export interface ControllerArtifactInspectionContext {
  readonly machine: MachineDefinition | MachinePhysicalSnapshot;
  readonly binding: MachinePostBinding;
  readonly installation: PostInstallation;
  readonly properties: Readonly<Record<string, PostPropertyValue>>;
}

export interface ControllerArtifactInspection {
  readonly text: string;
  readonly fileName: string;
  readonly provenance: readonly { readonly label: string; readonly value: string }[];
  readonly options?: GCodeInspectionOptions;
}

/** Inspection uses the generated bytes and pinned context, never the currently selected setup. */
export async function createControllerArtifactInspection(
  artifact: ControllerProgramArtifact,
  context: ControllerArtifactInspectionContext
): Promise<ControllerArtifactInspection> {
  const provenance = [
    { label: 'Saved revision', value: artifact.revisionId },
    { label: 'Artifact SHA-256', value: artifact.sha256 },
    { label: 'Exact post', value: `${artifact.post.packageId}@${artifact.post.version}` },
    { label: 'Post SHA-256', value: artifact.post.contentHash },
    { label: 'UPID SHA-256', value: artifact.revisionHashes.upid },
    { label: 'Machine SHA-256', value: artifact.revisionHashes.machine },
    { label: 'Setup SHA-256', value: artifact.revisionHashes.binding }
  ];
  // Oversized artifacts keep their exact download, without building an unusable per-line context.
  if (validateGCodeInspectionSource(artifact.text)) return { text: artifact.text, fileName: artifact.fileName, provenance };
  const { bindings: _bindings, activeBindingId: _activeBindingId, ...physical } = context.machine as MachineDefinition;
  const hashes = await Promise.all([hashJson(physical), hashJson(context.binding), hashJson(context.properties)]);
  const ref = context.installation.ref;
  const exact = ref.packageId === artifact.post.packageId && ref.version === artifact.post.version &&
    ref.contentHash === artifact.post.contentHash && ref.contentHash === artifact.revisionHashes.postPackage &&
    hashes[0] === artifact.revisionHashes.machine && hashes[1] === artifact.revisionHashes.binding &&
    hashes[2] === artifact.revisionHashes.postProperties;
  const serialized = serializeControllerOutput(artifact.program, artifact.output);
  if (!exact || !serialized.ok || serialized.text !== artifact.text) {
    provenance.push({ label: 'Inspection context', value: 'Pinned setup context does not match this artifact. Generic interpretation assumptions apply.' });
    return { text: artifact.text, fileName: artifact.fileName, provenance };
  }
  provenance.push({ label: 'Physical machine', value: `${physical.name} (${physical.id})` },
    { label: 'Saved setup', value: `${context.binding.name} (${context.binding.id})` },
    { label: 'Post dialect', value: context.installation.package.dialect.id });
  const commands = context.installation.package.dialect.commands;
  const scope = `${context.installation.package.dialect.id} · ${artifact.post.contentHash}`;
  const lineContexts: NonNullable<GCodeInspectionOptions['lineContexts']>[number][] = [];
  for (const block of artifact.program.blocks) {
    const descriptions: NonNullable<NonNullable<GCodeInspectionOptions['lineContexts']>[number]['commands']>[number][] = [];
    const centerModes = new Set<'absolute' | 'incremental'>();
    let motionRepresentable = !block.motion;
    for (const id of block.commandIds) {
      const command = commands[id];
      if (!command) continue;
      // Only complete literal G/M words are described. Arbitrary post templates remain unknown.
      const codes = command.template.match(/\b[GM](?:\d+(?:\.\d+)?)(?=\s|$)/gi) ?? [];
      const compensation = command.effects.includes('compensation.off') ? 'off'
        : command.effects.includes('compensation.left') ? 'left'
        : command.effects.includes('compensation.right') ? 'right' : undefined;
      for (const token of codes) descriptions.push({ code: token[0].toUpperCase() + Number(token.slice(1)),
        meaning: `${id}: ${command.effects.join(', ')}`, scope, ...(compensation ? { compensation } : {}) });
      if (block.motion) {
        const xy = roleWord(command, 'motion.end-x', 'X') && roleWord(command, 'motion.end-y', 'Y');
        const motionCodes = codes.map(token => token[0].toUpperCase() + Number(token.slice(1))).filter(token => /^G[0123]$/.test(token));
        const code = motionCodes.length === 1 ? motionCodes[0] : undefined;
        const numericFormat = Object.values(command.parameters).every(parameter =>
          !('format' in parameter) || parameter.format.decimalSeparator === '.');
        motionRepresentable ||= xy && numericFormat && (block.motion.motion === 'linear'
          ? code === 'G0' || code === 'G1'
          : roleWord(command, 'motion.center-x', 'I') && roleWord(command, 'motion.center-y', 'J') &&
            ((code === 'G2' && command.arcDirection === 'clockwise') || (code === 'G3' && command.arcDirection === 'counterclockwise')));
      }
      if (block.motion?.motion !== 'circular') continue;
      for (const parameter of Object.values(command.parameters)) {
        if (!('centerReference' in parameter)) continue;
        const mode = parameter.centerReference.kind === 'fixed' ? parameter.centerReference.mode
          : context.properties[parameter.centerReference.property];
        if (mode === 'absolute' || mode === 'incremental') centerModes.add(mode);
      }
    }
    lineContexts.push({ line: artifact.output.programEnvelope.prefix.length + block.lineIndex + 1,
      ...(centerModes.size === 1 ? { ijMode: [...centerModes][0] } : {}), commands: descriptions,
      ...(!motionRepresentable || (block.motion?.motion === 'circular' && centerModes.size !== 1)
        ? { previewUnsupported: 'The exact saved post motion cannot be represented by conventional XY/IJ inspection. Its source and audited artifact remain available.' } : {}) });
  }
  provenance.push({ label: 'Geometry context', value: 'Audited generated coordinates use millimeters and absolute XY endpoints. Arc centers use the exact saved post/setup declarations; compensation is annotation only.' });
  return { text: artifact.text, fileName: artifact.fileName, provenance,
    options: { profile: 'neutral', defaults: { units: 'mm', xyMode: 'absolute',
      initialPosition: artifact.program.blocks.find(block => block.motion)?.motion?.start }, lineContexts } };
}

function roleWord(command: PostInstallation['package']['dialect']['commands'][string], role: string, letter: string) {
  const parameters = Object.entries(command.parameters).filter(([, parameter]) => parameter.role === role);
  if (parameters.length !== 1) return false;
  const [name] = parameters[0];
  return new RegExp(`(?:^|\\s)${letter}\\{${name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\}(?=\\s|$)`, 'i').test(command.template);
}

async function hashJson(value: unknown) {
  const bytes = new TextEncoder().encode(canonicalJson(JSON.parse(JSON.stringify(value))));
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, '0')).join('');
}
