import { act } from 'react';
import { createRoot } from 'react-dom/client';
import { expect, it, vi } from 'vitest';

import type { ExecutionSpatialAction } from '@/domain/editor/executionSpatialActions';
import { createPathPlanningDocumentFromDxfEntities } from '@/domain/path-intel/fromDxfEntities';
import { EditorPreview } from '../EditorPreview';

it('keeps coincident authored and generated pauses individually selectable', () => {
  const pathDocument = createPathPlanningDocumentFromDxfEntities([
    { type: 'circle', layer: 'CUT', center: { x: 0, y: 0 }, radius: 5 }
  ]);
  const point = { x: 5, y: 0 };
  const actions: ExecutionSpatialAction[] = [
    { key: 'stop:op:check', eventId: 'stop', eventKind: 'program-stop',
      operationId: pathDocument.plan.operations[0].id, point, label: 'Authored stop',
      detail: 'Authored in Program Stops', pause: 'authored', emittedPauseCommandIds: [], stopId: 'check' },
    { key: 'transition:op:thread', eventId: 'thread', eventKind: 'wire-thread',
      operationId: pathDocument.plan.operations[0].id, point, label: 'Manual rethread pause',
      detail: 'Generated by Between Contours', pause: 'generated-manual-thread', emittedPauseCommandIds: [] }
  ];
  const container = document.createElement('div');
  document.body.appendChild(container);
  const root = createRoot(container);
  const onSelect = vi.fn();
  try {
    act(() => root.render(<EditorPreview program={null} pathDocument={pathDocument}
      hoveredLine={null} measurementPoints={[]} pinnedLines={[]} selectedLines={[]}
      spatialActions={actions} onSelectSpatialAction={onSelect} />));
    const group = container.querySelector('[data-preview-pause-group]');
    expect(group?.textContent).toContain('2 pauses');
    act(() => group?.querySelector('[data-preview-pause-hit]')?.dispatchEvent(
      new MouseEvent('click', { bubbles: true })));
    expect(group?.textContent).toContain('Authored stop');
    expect(group?.textContent).toContain('Manual rethread pause');
    const generatedRow = [...group?.querySelectorAll('g') ?? []].find((node) =>
      node.textContent === 'Manual rethread pause');
    act(() => generatedRow?.dispatchEvent(new MouseEvent('click', { bubbles: true })));
    expect(onSelect).toHaveBeenCalledWith('transition:op:thread');
  } finally {
    act(() => root.unmount());
    container.remove();
  }
});
