import { act } from 'react';
import { createRoot } from 'react-dom/client';
import { expect, it, vi } from 'vitest';
import { createPathPlanningDocumentFromDxfEntities } from '@/domain/path-intel/fromDxfEntities';
import { EditorPreview } from '../EditorPreview';

(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

it.each(['point', 'select'] as const)('lets %s point-picking pick a coordinate covered by a spatial action marker', (mode) => {
  const document = createPathPlanningDocumentFromDxfEntities([
    { type: 'circle', layer: 'CUT', center: { x: 0, y: 0 }, radius: 5 }
  ]);
  const container = window.document.createElement('div');
  window.document.body.append(container);
  const root = createRoot(container);
  const onPick = vi.fn();
  const onSelectAction = vi.fn();
  try {
    act(() => root.render(<EditorPreview program={null} pathDocument={document}
      canvasMouseMode={mode} onPreviewPointClick={onPick} onSelectSpatialAction={onSelectAction}
      hoveredLine={null} measurementPoints={[]} pinnedLines={[]} selectedLines={[]}
      spatialActions={[{ key: 'thread', eventId: 'thread', eventKind: 'wire-thread',
        operationId: document.plan.operations[0].id, point: { x: 5, y: 0 },
        label: 'Manual rethread pause', detail: 'Generated by Between Contours',
        pause: 'generated-manual-thread', emittedPauseCommandIds: [] }]} />));
    const svg = container.querySelector('svg[data-preview-model]');
    if (!svg) throw new Error('Missing preview');
    Object.defineProperty(svg, 'getBoundingClientRect', { value: () => ({
      x: 0, y: 0, left: 0, top: 0, right: 700, bottom: 500, width: 700, height: 500
    }) });
    expect(svg.contains(container.querySelector('[data-preview-pause-hit]'))).toBe(true);
    act(() => container.querySelector('[data-preview-pause-hit]')!.dispatchEvent(
      new MouseEvent('click', { bubbles: true, clientX: 350, clientY: 250 })));
    expect(onSelectAction).not.toHaveBeenCalled();
    expect(onPick).toHaveBeenCalledOnce();
  } finally {
    act(() => root.unmount());
    container.remove();
  }
});
